FROM python:3.13-slim-bookworm

# 设置非交互模式
ENV DEBIAN_FRONTEND=noninteractive
ENV EXIFTOOL_PATH=/usr/bin/exiftool
ENV FFMPEG_PATH=/usr/bin/ffmpeg



# 安装运行时依赖
RUN apt-get update && apt-get install -y --no-install-recommends \
    ffmpeg \
    exiftool \
    procps \
    zip \
    unzip \
    vim \
    fontconfig \
    xfonts-utils \
    curl \
    && rm -rf /var/lib/apt/lists/*

# 安装 uv
COPY --from=ghcr.io/astral-sh/uv:0.7.20   /uv /usr/local/bin/uv

# 设置 uv 清华镜像源
ENV UV_INDEX_URL=https://pypi.mirrors.ustc.edu.cn/simple/

WORKDIR /app

# 创建虚拟环境
RUN uv venv /app/.venv
ENV PATH="/app/.venv/bin:$PATH"
ENV VIRTUAL_ENV=/app/.venv

# 先复制依赖声明文件（利用 Docker 缓存层）
COPY pyproject.toml ./

# 使用 uv 安装依赖（在 venv 中）
RUN uv sync --no-cache --no-install-project 

# 再复制项目源码
COPY . /app

# 安装本地 markitdown 包
RUN uv pip install --no-cache \
    -e /app/markitdown/packages/markitdown[all] \
    -e /app/markitdown/packages/markitdown-sample-plugin

# # 安装字体
# RUN mkdir -p /usr/share/fonts/my_fonts && \
#     unzip -j Fonts.zip -d /usr/share/fonts/my_fonts && \
#     mkfontscale /usr/share/fonts/my_fonts && \
#     rm Fonts.zip

# 启动命令
ENTRYPOINT ["uvicorn", "server:app", "--host", "0.0.0.0"]
CMD ["--port", "5000", "--workers", "4"]
